src/pages/start/9.learn-more.mdx

Found an extraneous "g" on the URL for the "Declarative management of dotfiles with Nix and Home Manager" link.

Fix URL typo on Learn More page

---

flake.nix
src/pages/start/5.nix-search.mdx

I noticed that there is a missing hash, and somehow CI didn't catch it; this is likely because even though it _was_ caught by one of the scripts `ci` runs, `ci` doesn't fail when it encounters an error.

flake: ci script should fail on error

---

.github/workflows/test.yml

This means that external contributors can actually have their CI run
without needing to rebuild the world (without this key, any hits from
cache.nixos.org will not be used due to a lack of a trusted signature).
---
PR from outside to validate that this does what we expect for external contributors.

test: don't make cache.nixos.org pubkey a secret

---

src/pages/start/6.dev-shell-flake.mdx

Bringing the output inline w/ the other languages and accurate with the output for `type gcc`

Update to reflect the output for cpp

---

nix/templates/pkg/cpp/flake.nix

Noticed this while going through the tutorial.
The description should say C++ instead of Python.

c++: pkg: fix incorrect description in example

---

nix/templates/pkg/python/setup.py

Fixes https://github.com/DeterminateSystems/zero-to-nix/issues/193.
---
You can validate with:
```
nix flake init --template "github:DeterminateSystems/zero-to-nix/fix-wrong-command#python-pkg"
nix build
./result/bin/zero-to-nix-python
```

Fix python template using wrong binary name

---

src/pages/start/2.nix-run.mdx

Fixes https://github.com/DeterminateSystems/zero-to-nix/issues/158.
---
Rather than trying to work in the "installable" term, I just corrected what "flake reference" was referring to -- `nixpkgs`, not `nixpkgs#ponysay`.

start/nix-run: `nixpkgs` is the flake ref, `nixpkgs#ponysay` is not

---

flake.nix
nix/shell/example.nix
src/pages/start/4.nix-develop.mdx

For the sake of clarity we removed the shell hooks from the example dev environments. This PR adds a quick example for users to run.

Add shell hook example

---

src/assets/css/prose.css
src/pages/start/1.install.mdx
vale/Vocab/Docs/accept.txt

I've seen concerns about "curl to Bash" in a few corners. This seems like a reasonable way to address those.

Add non-curl-to-Bash installation option

---

CONTRIBUTING.md
src/pages/start/1.install.mdx
vale/Vocab/Docs/accept.txt

Having a CONTRIBUTING.md is kind of an emerging standard that I'd like to adopt. This PR moves the contributing guideline there, which has the pleasant consequence of removing some text from the install guide.

Add separate contributing guide

---

nix/templates/dev/rust/flake.nix

Add libiconv dependency for macOS in Rust dev env

---

nix/shell/example.nix

Verified this fixes #200
```shell
zero-to-nix on  bugfix/rust-example via  v16.19.0
❯ cd nix/shell
zero-to-nix/nix/shell on  bugfix/rust-example
❯ rustc --version
rustc 1.69.0-nightly (001a77fac 2023-01-30)
zero-to-nix/nix/shell on  bugfix/rust-example
❯ cat example.nix | rg rust -B5
shellHook = ''
echo "Welcome to a Nix development environment for Go!"
'';
};
rust = pkgs.mkShell {
packages = with pkgs; [ cargo rustc ];
zero-to-nix/nix/shell on  bugfix/rust-example
❯ nix develop ".#rust"
path '/home/will/code/zero-to-nix/nix/shell' does not contain a 'flake.nix', searching up
Welcome to a Nix development environment for Rust!
[will@betelgeuse:~/code/zero-to-nix/nix/shell]$ rustc --version
rustc 1.64.0
```

Fix rustc getting pulled in from user's env

---

src/pages/start/1.install.mdx

The current `exec $SHELL` instructions don't seem to work on all shells, whereas opening a new terminal seems to do the job irrespective of preferred shell.

Update post-installation instructions

---

src/pages/start/1.install.mdx

This should help to establish proper expectations of the quick start for would-be readers, some of whom have criticized the quick start for being a bit thin. Those folks aren't *wrong*, but they may be better served by being alerted that they aren't the target audience per se.

Add audience clarification in quick start

---

src/layouts/base.vue

It seems every page gets its the root index as its canonical, which is causing some indexing problems. We should get the canonical tag back, but I think this is a good short term solution.

Drop the canonical tag

---

nix/templates/dev/cpp/flake.nix
nix/templates/dev/go/flake.nix
nix/templates/dev/haskell/flake.nix
nix/templates/dev/javascript/flake.nix
nix/templates/dev/python/flake.nix

This is a tiny nit, but aarch64 is ARM and isn't made by AMD and ARM doesn't make anything that runs x86_64 that I know of. I had to Google that when I init'd with this template, so I assumed others would appreciate not having to look it up.
Thanks for a fantastic set of docs!

Fix system architecture comments in templates

---

src/pages/concepts/sandboxing.mdx

Link destination was missing. 
Full disclosure - I'm not 100% positive I did this right, but it looks pretty simple; I just copied the syntax from other link defs in the file / related files, and it appears to be the same. Hopefully it works!

Fix link destination for provenance concept.

---

src/pages/start/3.nix-develop.mdx

Tiny documentation fix for broken link in the guide:

fix(docs): link to flake outputs

---

src/pages/start/7.learn-more.mdx

The current link (https://nix.dev/tutorials/building-and-running-docker-images) is now broken. The correct link is: https://nix.dev/tutorials/nixos/build-and-deploy/building-and-running-docker-images

Fix broken nix.dev link in 7.learn-more.mdx

---

src/pages/start/7.learn-more.mdx

The URL for "Building and running Docker images" results in a 404 at nix.dev. This change points to, what I believe to be, the current version of that document. Especially if the [current google cache](https://webcache.googleusercontent.com/search?q=cache%3A9hulwhM6SWEJ%3Ahttps%3A%2F%2Fnix.dev%2Ftutorials%2Fnixos%2Fbuild-and-deploy%2Fbuilding-and-running-docker-images&cd=9&hl=en&ct=clnk&gl=us) for that URL is correct.

Fix nix.dev url for Building and running Docker images

---

.github/workflows/test.yml

An assortment of GitHub Workflow changes, potentially including:
- Enable DeterminateSystems/magic-nix-cache-action@main
- Reference all DeterminateSystems actions via @main
- Make update.yaml consistent across repos
- Remove unnecessary github-token: from nix-installer-action
- Update actions/checkout@v2 to actions/checkout@v3

DS-970: Add Magic Nix Cache and other workflow changes

---

src/pages/start/1.install.mdx

As of [`v0.9.0`][release], the Determinate Nix Installer [supports SELinux-enabled systems][pr] (thanks, @Hoverbear!). The quick start install page still mentions SELinux systems as being unsupported- let's update the install page to reflect this change.
Resolves #267
[release]: https://github.com/DeterminateSystems/nix-installer/releases/tag/v0.9.0
[pr]: https://github.com/DeterminateSystems/nix-installer/pull/465

Remove "no SELinux" specifier from Linux in supported platforms list

---

src/pages/concepts/derivations.mdx

The derivation wrappers for rust and python point to nixos docs and it looks like the go one was supposed to as well, but currently it points to https://go.dev

Update link to buildgomodule in derivations.mdx

---

src/pages/start/4.nix-build.mdx

`bat` package has been moved recently (see [ec5b438](https://github.com/NixOS/nixpkgs/commit/ec5b43883a118aec791a273d739048eaf8b88a2a))

Fix: link to `bat` package

---

src/pages/concepts/flakes.mdx

https://riff.sh seems down and the GitHub project is archived. I picked an alternate kinda arbitrarily. Suggestions welcome, or close this and rewrite as desired.

Replace broken Riff link with an alternate

---

nix/templates/pkg/go/flake.nix
nix/templates/pkg/javascript/flake.nix

The package templates for Go and Javascript, which are both referenced on the 'Build a package using Nix' page, have become outdated due to automated dependency updates (these should probably be disabled for templates?).
Users who try to execute the examples receive an error when trying a `nix build` on these examples:
```console
$ nix build
error: hash mismatch in fixed-output derivation '/nix/store/s5yjx...-zero-to-nix-go-go-modules.drv':
specified: sha256-pYnN8rxXNNLRegvJySwAyMUPBmnhSiDSHfMQpjB9Qjs=
got:    sha256-Cy1/QqbO2MyYgqJZKxrt1FZzLSgXbhSK3ceFPUlFujw=
error: 1 dependencies of derivation '/nix/store/d49n...-zero-to-nix-go.drv' failed to build
```
Supersedes / Closes #341 and closes #343, which have both been apparently overlooked.
Fixes #348 and fixes #331

Update checksums in package templates

---

flake.lock
nix/shell/example.nix
src/briefs/nix-installer-differences.mdx
src/pages/start/3.nix-develop.mdx
styles/config/vocabularies/Docs/accept.txt

Terraform is no longer considered free in Nixpkgs. We _could_ set `allowUnfree = true` in Nixpkgs to get around this but generally easier to just switch to a free package.

Use OpenTofu in dev shell instead of Terraform

---

src/pages/start/3.nix-develop.mdx

the flake uses 3.11 https://github.com/DeterminateSystems/zero-to-nix/blob/f3e82bac5b1b0da67ee53185d72c7be4c91e63b0/nix/templates/dev/python/flake.nix#L31

python sample version 3.nix-develop.mdx

---

src/components/Breadcrumb.astro

AlpineJS is currently throwing this warning on some pages:
```
Uncaught ReferenceError: breadcrumb is not defined
anonymous https://zero-to-nix.com/_astro/page.CwLfWgBQ.js line 5 > AsyncFunction:3
Ar https://zero-to-nix.com/_astro/page.CwLfWgBQ.js:5
br https://zero-to-nix.com/_astro/page.CwLfWgBQ.js:1
<anonymous> https://zero-to-nix.com/_astro/page.CwLfWgBQ.js:5
n https://zero-to-nix.com/_astro/page.CwLfWgBQ.js:5
wi https://zero-to-nix.com/_astro/page.CwLfWgBQ.js:5
D https://zero-to-nix.com/_astro/page.CwLfWgBQ.js:1
fr https://zero-to-nix.com/_astro/page.CwLfWgBQ.js:1
<anonymous> https://zero-to-nix.com/_astro/page.CwLfWgBQ.js:5
n https://zero-to-nix.com/_astro/page.CwLfWgBQ.js:5
r https://zero-to-nix.com/_astro/page.CwLfWgBQ.js:5
Mr https://zero-to-nix.com/_astro/page.CwLfWgBQ.js:5
C …
```

Fix AlpineJS warning

---

.github/workflows/flakehub-cache.yml

Just a bit of housekeeping. This param is not meaningful for this Action.

Remove use-flakehub param in CI

---

src/content/concepts/channels.mdx

Page was [renamed last year](https://wiki.nixos.org/w/index.php?title=Channel_branches&diff=11235&oldid=11234), which probably explains why the unofficial wiki was used here instead, since they did not rename their version.

Reference official wiki's version of page

---

nix/templates/pkg/javascript/flake.nix
src/content/start/4.nix-build.mdx

Using the fancy function for loading the javascript package.json means you don't need to use a hard-coded hash.

Obviate needing the explicit javascript hash

---

nix/shell/example.nix

This `python39` package no longer exists, which is breaking the Python example dev shell.
Updating to a more modern Python fixes this.
Fixes #432

Fix Python dev shell
