DeterminateSystems/zero-to-nix

src/pages/concepts/nix-language.mdx
=> clarify function application syntax

src/components/layout/Navbar.vue
This will make the provenance of the site a bit more clear.
=> Add DS link to navbar title

src/pages/concepts/nixos.mdx
=> Remove mention of stateVersion

nix/templates/pkg/javascript/flake.nix, nix/templates/pkg/javascript/package-lock.json
Fixes `nix build` issues in PR #174
=> Add missing pieces to JavaScript package build

src/pages/start/7.nix-build-flake.mdx
=> Make browser open step system independent

nix/templates/dev/python/flake.nix
=> Rework Python dev environment

src/pages/start/1.install.mdx
@Hoverbear This PR is largely a placeholder so you can give me the complete list here in the comments 🤣 It also might be nice to present this in a more visually appealing way but text is fine for now.
Fixes #181
=> List supported platforms for Nix Installer

nix/templates/pkg/javascript/flake.nix, nix/templates/pkg/javascript/package-lock.json
=> Fix JavaScript package build

src/pages/concepts/index.vue, src/pages/start/index.vue
=> Fix page titles issue

iles.config.ts, src/layouts/base.vue, src/site.ts
This PR fixes the issue temporarily addressed in #228
=> Fix canonical URL

src/pages/start/1.install.mdx, vale/Vocab/Docs/accept.txt
This update tracks changes to the installer introduced in [v0.3.0](https://docs.rs/nix-installer/0.3.0/nix_installer).
=> Update Nix Installer support list

src/assets/css/prose.css, src/components/layout/CookieConsent.vue
=> Fix cookie widget color issue

flake.nix, nix/templates/dev/cpp/flake.nix, nix/templates/dev/go/flake.nix, nix/templates/dev/haskell/flake.nix, nix/templates/dev/javascript/flake.nix, nix/templates/dev/python/flake.nix, nix/templates/dev/rust/flake.nix, nix/templates/pkg/cpp/flake.nix, nix/templates/pkg/go/flake.nix, nix/templates/pkg/haskell/flake.nix, nix/templates/pkg/javascript/flake.nix, nix/templates/pkg/python/flake.nix, nix/templates/pkg/rust/flake.nix, src/pages/concepts/flakes.mdx
A minor ergonomic improvement but a nice little win
=> Switch to built-in genAttrs function

nix/templates/dev/rust/flake.nix
=> Fix error in Rust env due to missing systems

.github/workflows/test.yml, src/pages/concepts/flakes.mdx
=> Provide clarity around lib outputs

.github/workflows/test.yml, nix/templates/pkg/scala/flake.nix, scripts/check-flake-templates.sh
Fixes #272 and adds some CI logic that should make this less likely in the future
=> Update Scala hash

src/pages/concepts/flakes.mdx
=> Fix typo in flakes concept

nix/templates/pkg/rust/flake.nix
=> Fix Rust package build

netlify.toml
If this makes it work, this is going to suck.
=> Add more redirects

README.md
=> fixed README url.

src/pages/concepts/nix-language.mdx, src/pages/concepts/pinning.mdx
- Fix tense error in nix-language.mdx
- Update phrase in pinning.mdx, a quick search shows this https://www.merriam-webster.com/dictionary/in%20relation%20to but not many results for the previous text
=> Small grammatical fixes

src/pages/concepts/channels.mdx, src/pages/start/5.nix-search.mdx
=> Update number of packages in nixpkgs

src/pages/start/2.nix-run.mdx, src/pages/start/3.nix-develop.mdx, src/pages/start/4.nix-build.mdx, src/pages/start/5.nix-search.mdx
=> Use Nixpkgs from FlakeHub in quick start

.github/workflows/test.yml
This is causing issues for external contributors. I'll find another solution to this that let's burdensome for others. But I'd like to get this through to unblock PRs like #354.
=> Make link checker action not fail

src/plugins/code.ts
While working on #372 and running `format`, there was out-of-date formatting.
=> chore: format

astro.config.mjs, src/components/Banner.astro, src/components/Dropdown.astro, src/layouts/Layout.astro
I meant to remove this before but forgot. This is likely to produce a FOUC on many refreshes.
=> Remove x-cloak from top-level html element

astro.config.mjs, package.json, pnpm-lock.yaml
- **Open external links in new tab**
- **Move config into mdx settings**
=> Open external links in new tab

astro.config.mjs, src/components/mdx/NixStorePath.astro
#388 accidentally broke all the [Expressive Code](https://expressive-code.com) code samples. This PR fixes that.
=> Fix code samples

src/components/Head.astro
Just a few missing items in the page metadata
=> Add missing SEO metadata

src/assets/css/main.css, src/components/Banner.astro, src/components/Head.astro, src/site.ts
Fixes #403 and makes the styling a bit more pleasant.
=> Fix up banner

.github/workflows/ci.yml, README.md, scripts/build-example-dev-shells.sh, scripts/build-pkg-templates.sh
This PR adds a checker script that presumably would've caught the error reported in #432
=> Add script to check dev shells

flake.lock, package.json, pnpm-lock.yaml
This fixes a Dependabot warning about the `form-data` library.
=> Update npm dependencies

src/content/concepts/dev-env.mdx
Added link to the derivation concept
=> Update dev-env.mdx to add link to derivation concept
